### PR TITLE
Add alter implementation

### PR DESCRIPTION
**Pull request by RaoulHC**
Not sure if this is the best implementation but it works like the regular `Map` version, and I don't think it should have worse asymptotics. 

Can look at adding a test suite if that would be useful.

### CODE REVIEW

**Comment by RaoulHC** [comment]
@dmwit could be reviewed/merged?

**Comment by dmwit** [comment]
Seems reasonable. Probably the best implementation would use `Map`'s `alterF` to look up and update one of the two maps at the same time, but this is also fine.

**Comment by RaoulHC** [comment]
Could this get in a release on hackage @dmwit?

**Comment by dmwit** [comment]
It is done.

**Pull request merged**
